iai-callgrind/iai-callgrind

- CHANGELOG.md
- README.md
- benchmark-tests/benches/test_lib_bench_groups.rs
- iai-callgrind-macros/src/lib.rs
- iai-callgrind/src/lib.rs
- iai-callgrind/tests/ui/test_library_benchmark_invalid_attributes.stderr
- iai-callgrind/tests/ui/test_library_benchmark_invalid_bench_arguments.rs
- iai-callgrind/tests/ui/test_library_benchmark_invalid_bench_arguments.stderr
- iai-callgrind/tests/ui/test_library_benchmark_invalid_bench_arguments_key_value.stderr
- iai-callgrind/tests/ui/test_library_benchmark_invalid_bench_arguments_when_config.rs
- iai-callgrind/tests/ui/test_library_benchmark_invalid_bench_arguments_when_config.stderr
- iai-callgrind/tests/ui/test_library_benchmark_invalid_bench_id.rs
- iai-callgrind/tests/ui/test_library_benchmark_invalid_bench_id.stderr
- iai-callgrind/tests/ui/test_library_benchmark_valid_benches_arguments.rs
This pr adds the possibility to specify multiple benchmarks in one go in a single `benches` attribute
From the documentation:
```rust
// You can use the `benches` attribute to specify multiple benchmark runs in one go. You can specify
// multiple `benches` attributes or mix the `benches` attribute with `bench` attributes.
#[library_benchmark]
// This is the simple form. Each `,`-separated element is another benchmark run and is passed to the
// benchmarking function as parameter. So, this is the same as specifying two `#[bench]` attributes
// #[bench::multiple_0(vec![1])] and #[bench::multiple_1(vec![5])].
#[benches::multiple(vec![1], vec![5])]
// You can also use the `args` argument to achieve the same. Using `args` is necessary if you also
// want to specify a `config` or `setup` …
```
> Add support for specifying multiple benchmarks within a single `benches` attribute

- iai-callgrind-runner/src/runner/tool/mod.rs
This pr fixes an error when `--load-baseline` loads and compares with the dataset from `--baseline`.
> Fix `--load-baseline`

- iai-callgrind-runner/src/runner/args.rs
`cargo bench` allows to specify a filter for benchmark names as positional argument. This positional argument is passed through to the `iai-callgrind-runner` which isn't able to handle positional arguments and exits with error.
This pr fixes it by ignoring any positional arguments.
> Fix: positional arguments from `cargo bench` cause iai-callgrind to exit with error

- .dicts/custom.txt
- Justfile
- benchmark-tests/benches/test_bench.rs
- benchmark-tests/benches/test_lib_bench_single.conf.yml
- benchmark-tests/benches/test_lib_bench_single.rs.j2
- benchmark-tests/benches/test_lib_bench_single.stdout.1
- benchmark-tests/benches/test_lib_bench_single.stdout.3
- iai-callgrind-runner/src/runner/args.rs
- iai-callgrind-runner/src/runner/meta.rs
- iai-callgrind-runner/src/runner/mod.rs
- iai-callgrind/src/macros.rs
This pr is a follow up to #86 and adds support to filter benchmarks by BENCHNAME
```
cargo bench BENCHNAME
```
Also, the usage in `--help` is fixed to show `Usage: cargo bench ...` instead of the misleading `Usage: iai-callgrind-runner ...`.
> feat: Add support to filter benchmarks by name

- .dicts/custom.txt
- .github/workflows/cicd.yml
- client-request-tests/src/bin/valgrind-wrapper.rs
- client-request-tests/tests/fixtures/memcheck-reqs-test.armv7.stderr
- client-request-tests/tests/fixtures/memcheck-reqs-test.stderr
- client-request-tests/tests/fixtures/valgrind-reqs-test.freebsd.stderr
- client-request-tests/tests/test_client_requests/valgrind.rs
- iai-callgrind-runner/src/util.rs
- scripts/freebsd_build_and_test.sh
- scripts/freebsd_print_info.sh
- scripts/freebsd_run_tests.sh
This pr also adds running the build and all tests on FreeBSD
> Fix iai-callgrind-runner binary benchmarks were not able to copy fixtures on FreeBSD

- iai-callgrind/build.rs
Since valgrind 3.23.0 supports client requests for aarch64/freebsd. This pr adds this target to the supported targets for the optimized rust inline assembly.
> Support for optimized asm instructions on aarch64 freebsd

- README.md
- benchmark-tests/Cargo.toml
- benchmark-tests/benches/test_lib_bench_cache_sim.stdout.2
- benchmark-tests/benches/test_lib_bench_compare.conf.yml
- benchmark-tests/benches/test_lib_bench_compare.expected.1.yml
- benchmark-tests/benches/test_lib_bench_compare.rs
- benchmark-tests/benches/test_lib_bench_compare.stdout.1
- benchmark-tests/benches/test_lib_bench_single.stdout.3
- benchmark-tests/src/bench.rs
- benchmark-tests/src/lib.rs
- iai-callgrind-runner/schemas/summary.v1.schema.json
- iai-callgrind-runner/src/api.rs
- iai-callgrind-runner/src/runner/costs.rs
- iai-callgrind-runner/src/runner/format.rs
- iai-callgrind-runner/src/runner/lib_bench.rs
- iai-callgrind-runner/src/runner/summary.rs
- iai-callgrind/src/macros.rs
- iai-callgrind/tests/ui/test_main_invalid_library_benchmark_groups.stderr
This pr adds support for comparing benchmark functions specified in a `library_benchmark_group!`. Only the benches with the same id of the `#[bench::id(...)]` attribute are compared.
Closes #37
> Support comparing library benchmark functions by `#[bench]` id (#37)

- iai-callgrind/Cargo.toml
- iai-callgrind/build.rs
`iai-callgrind`'s build dependencies are only used when the "client_requests_defs" feature is enabled, and as such should be marked optional to avoid compiling them when this feature is not enabled.
I have also included a fix to suppress cargo's `--check-cfg` warnings (beta, nightly only for now).
> chore: mark build deps as optional

- Cargo.lock
- Cargo.toml
- iai-callgrind/Cargo.toml
- iai-callgrind/build.rs
Fix the `rust-check-cfg` iai-callgrind build script prints introduced in #175.
We need to check the currently active rust version (rust-check-cfg was introduced in 1.80), to avoid compiler warnings if `rust-check-cfg` is printed although the rust version is < 1.80. Also, the different values need to be printed in a single statement following the syntax `rust-check-cfg=cfg(key, values("value1","value2",...))`
> fix: Print rust-check-cfg only if rust version >= 1.80.0

- iai-callgrind-macros/src/lib.rs
- iai-callgrind/src/macros.rs
Clarification on uniqueness & matching of bench IDs
> #169 Doc comment on bench id uniqueness

- .github/workflows/cicd.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- benchmark-tests/Cargo.toml
- benchmark-tests/benches/test_lib_bench_setup_and_teardown.rs
- iai-callgrind-macros/src/lib.rs
- iai-callgrind/tests/ui/test_library_benchmark_invalid_arguments.rs
- iai-callgrind/tests/ui/test_library_benchmark_invalid_arguments.stderr
- iai-callgrind/tests/ui/test_library_benchmark_invalid_attributes.stderr
- iai-callgrind/tests/ui/test_library_benchmark_invalid_bench_arguments.stderr
- iai-callgrind/tests/ui/test_library_benchmark_invalid_bench_arguments_key_value.stderr
- iai-callgrind/tests/ui/test_library_benchmark_invalid_bench_arguments_when_config.stderr
- iai-callgrind/tests/ui/test_library_benchmark_invalid_bench_setup_and_teardown.rs
- iai-callgrind/tests/ui/test_library_benchmark_invalid_bench_setup_and_teardown.stderr
- iai-callgrind/tests/ui/test_library_benchmark_invalid_setup_and_teardown.rs
- iai-callgrind/tests/ui/test_library_benchmark_invalid_setup_and_teardown.stderr
- iai-callgrind/tests/ui/test_library_benchmark_valid_setup_and_teardown.rs
This pr adds the possiblity to specify a teardown function in `#[bench]` and `#[benches]`
```rust
fn my_teardown(value: u64) {
println!("{value}");
}
#[library_benchmark]
#[bench::some_id(args = (), teardown = my_teardown)]
fn some_bench() -> u64 {
my_lib::some_func()
}
```
Here, `my_teardown` is called with the result of `my_lib::some_func()`. This works the same way for the `#[benches]` attribute.
For completeness and consistency the `#[bench]` attribute now also allows to specify a `setup` parameter. This wasn't strictly necessary because the args parameter takes expressions. Before this change it was possible to specify the setup function like so
```rust
fn my_setup(a: u64, b: u64) -> u64 {
a + b
}
#[library_benchmark]
#[bench::some_id(args = my_setup(2, 3))]
fn some_bench(value: u64) …
```
> Add teardown parameter to #[bench] and #[benches]. Add setup and teardown to #[library_benchmark].

- Cargo.lock
- Cargo.toml
- benchmark-tests/Cargo.toml
- benchmark-tests/benches/test_lib_bench_compiler_optimization.conf.yml
- benchmark-tests/benches/test_lib_bench_compiler_optimization.expected.1.yml
- benchmark-tests/benches/test_lib_bench_compiler_optimization.rs
- benchmark-tests/benches/test_lib_bench_generics.conf.yml
- benchmark-tests/benches/test_lib_bench_generics.expected.1.yml
- benchmark-tests/benches/test_lib_bench_generics.rs
- benchmark-tests/benches/test_lib_bench_setup_and_teardown.rs
- benchmark-tests/src/bench.rs
- iai-callgrind-macros/src/lib.rs
- iai-callgrind-runner/Cargo.toml
- iai-callgrind-runner/src/runner/bin_bench.rs
- iai-callgrind-runner/src/runner/callgrind/parser.rs
- iai-callgrind-runner/src/runner/lib_bench.rs
- iai-callgrind-runner/src/runner/mod.rs
- iai-callgrind-runner/tests/test_callgrind/test_flamegraph_parser.rs
- iai-callgrind-runner/tests/test_callgrind/test_sentinel_parser.rs
- iai-callgrind/src/bin_bench.rs
- iai-callgrind/tests/ui/test_library_benchmark_invalid_bench_arguments.stderr
This pr adds support for generic benchmark functions. 
Benchmark functions were exported under a different name `iai_callgrind::bench::FUNCTION_NAME` with `FUNCTION_NAME` being the original function name:
In short:
```rust
#[library_benchmark]
fn my_bench() -> u64 { 42 }
```
was roughly converted to
```rust
mod my_bench {
#[inline(never)]
#[export_name = "iai_callgrind::bench::my_bench"]
fn my_bench() -> u64 { 42 }
}
```
The main reason for having the different export name is to have a constant string we can match for in the callgrind output files. So, a function starting with `iai_callgrind::bench::` was the benchmark function. The compiler optimizes functions which are semantically equivalent
```rust
#[library_benchmark]
fn my_bench() -> u64 { 42 }
#[library_benchmark]
fn …
```
> fix(#198): Support generic benchmark functions

- iai-callgrind-runner/src/error.rs
- iai-callgrind-runner/src/runner/mod.rs
- iai-callgrind-runner/tests/common/mod.rs
- iai-callgrind-runner/tests/test_runner_binary/mod.rs
- iai-callgrind-runner/tests/test_runner_binary/test_version.rs
- iai-callgrind-runner/tests/tests.rs
Error messages as seen in #161 are not very helpful.
This pr adds better error messages with a solution hint if parsing the iai-callgrind-runner arguments fails. The parsing errors almost always happen because the iai-callgrind library and the iai-callgrind-runner binary have different versions. Also, the actual version check now takes place a lot sooner.
> iai-callgrind-runner: Provide better error message if the argument parsing of the runner itself fails

- client-request-tests/tests/fixtures/cachegrind-reqs-test.since_1.79.0.armv7.stderr
- iai-callgrind-runner/src/runner/callgrind/mod.rs
- iai-callgrind/src/client_requests/valgrind.rs
- iai-callgrind/src/lib.rs
- iai-callgrind/src/lib_bench.rs
- iai-callgrind/src/macros.rs
Fix various clippy warnings occurring since latest stable 1.80. Also, the stable release changed the output of the client requests on arm.
> lint: Fix clippy warnings

- iai-callgrind-runner/src/api.rs
- iai-callgrind-runner/src/runner/bin_bench.rs
- iai-callgrind-runner/src/runner/format.rs
- iai-callgrind-runner/src/runner/lib_bench.rs
- iai-callgrind/src/bin_bench.rs
- iai-callgrind/src/lib_bench.rs
This pr adds an option to `LibraryBenchmarkConfig` and `BinaryBenchmarkConfig` to make the truncation of the `DESCRIPTION` in the output header adjustable.
```
benchmark_file::group_name::function_name id:DESCRIPTION
Instructions:              352135|352135          (No change)
L1 Hits:                   470117|470117          (No change)
L2 Hits:                      748|748             (No change)
RAM Hits:                    4112|4112            (No change)
Total read+write:          474977|474977          (No change)
Estimated Cycles:          617777|617777          (No change)
```
Per default the `DESCRIPTION` is truncated to the width of 50 ascii characters but can be changed to any `usize` or switched off entirely.
Related #207
> feat(truncate): Support adjustable truncation of description in output header

- .dicts/custom.txt
- Justfile
- scripts/freebsd_build_and_test.sh
A few improvements for working with `just`. 
`just -l` now groups the rules and should provide a clearer overview. Also I've annotated the documentation of each rule with the usages like `Uses: cargo +nightly` or `Uses: npx prettier`. 
If `prettier` or `cspell` were not installed each `just` execution has shown `prettier not found`, `cspell not found`. This was some annoying unintended output.
> chore(just): Group recipes in Justfile. Fix output of command not found

- benchmark-tests/benches/test_lib_bench/main_and_group_setup_and_teardown/expected_stdout.1
- benchmark-tests/benches/test_lib_bench/main_and_group_setup_and_teardown/expected_stdout.2
- benchmark-tests/benches/test_lib_bench/main_and_group_setup_and_teardown/expected_stdout.3
- benchmark-tests/benches/test_lib_bench/main_and_group_setup_and_teardown/test_lib_bench_main_and_group_setup_and_teardown.conf.yml
- benchmark-tests/benches/test_lib_bench/main_and_group_setup_and_teardown/test_lib_bench_main_and_group_setup_and_teardown.rs
- iai-callgrind-runner/src/runner/lib_bench.rs
The teardown function in
```rust
library_benchmark_group!(name = my_group; teardown = some_func(); benchmarks = ...)
```
was not executed since the setup was not present, too.
This pr fixes it to the expected behaviour that a `library_benchmark_group!` teardown function is executed independently of the setup.
> Fix: group teardown in library benchmarks is not run when setup is not present

- benchmark-tests/Cargo.toml
- benchmark-tests/benches/test_bin_bench/client_requests/expected_stdout.1
- benchmark-tests/benches/test_bin_bench/client_requests/test_bin_bench_client_requests.conf.yml
- benchmark-tests/benches/test_bin_bench/client_requests/test_bin_bench_client_requests.rs
- benchmark-tests/src/helper/client-requests.rs
- iai-callgrind-runner/src/runner/callgrind/summary_parser.rs
using client_requests::callgrind::start_instrumentation() and stop_instrumentation() leads to summary with a "0" value skipping summary in that case to use totals which are present
> fix(summary_parser): extract "totals" when "summary" is "0"

- iai-callgrind-runner/src/runner/format.rs
Fixes the output of negative infinity from `[++-inf+++]` for the factor to `[---inf---]`.
In full context
```text
benchmark_file::group::function id
Instructions:                    0|2000                (-100.000%) [---inf---]
```
> Fix benchmark output format when factor is negative infinite

- .dicts/custom.txt
- CHANGELOG.md
- benchmark-tests/Cargo.toml
- benchmark-tests/benches/test_lib_bench/entry_point/test_lib_bench_entry_point.conf.yml
- benchmark-tests/benches/test_lib_bench/entry_point/test_lib_bench_entry_point.rs
- cspell.json
- docs/src/SUMMARY.md
- docs/src/benchmarks/library_benchmarks/custom_entry_point.md
- docs/src/client_requests.md
- docs/src/flamegraphs.md
- docs/src/images/flamegraph_diff.svg
- docs/src/images/flamegraph_regular.svg
- iai-callgrind-runner/src/api.rs
- iai-callgrind-runner/src/runner/callgrind/flamegraph_parser.rs
- iai-callgrind-runner/src/runner/callgrind/hashmap_parser.rs
- iai-callgrind-runner/src/runner/callgrind/parser.rs
- iai-callgrind-runner/src/runner/callgrind/sentinel_parser.rs
- iai-callgrind-runner/src/runner/format.rs
- iai-callgrind-runner/src/runner/lib_bench.rs
- iai-callgrind-runner/src/runner/meta.rs
- iai-callgrind-runner/src/runner/mod.rs
- iai-callgrind-runner/src/runner/tool/mod.rs
- iai-callgrind-runner/tests/fixtures/callgrind.out/callgrind.no_entry_point.cmd
- iai-callgrind/src/lib.rs
- iai-callgrind/src/lib_bench.rs
This pr adds the possibility to adjust the default toggle which Iai-Callgrind sets automatically in library benchmarks to the module path of the benchmark function. This new option therefore only affects library benchmarks.
There are cases in which this default toggle is just in the way, so it can also be switched off entirely.
Switching off the default toggle with `EntryPoint::None` helps especially when callgrind client requests are used. It is required to switch off the toggle and set `--collect-at-start=no` manually, so the instrumentation starts exactly where the client requests are called. Although not implemented (#255) yet, it will help to benchmark multithreaded/-process applications, since the default toggle needs to be switched off in such cases.
Setting a custom toggle with …
> feat: Add adjustable entry point (default toggle)

- Cargo.lock
- Cargo.toml
- client-request-tests/tests/fixtures/memcheck-reqs-test.armv7.stderr
- iai-callgrind-macros/Cargo.toml
- iai-callgrind-macros/src/bin_bench.rs
- iai-callgrind-macros/src/common.rs
- iai-callgrind-macros/src/derive_macros.rs
- iai-callgrind-macros/src/lib.rs
- iai-callgrind-macros/src/lib_bench.rs
Migrate to [proc-macro-error2]() since [proc-macro-error](https://crates.io/crates/proc-macro-error) is unmaintained (see https://rustsec.org/advisories/RUSTSEC-2024-0370) and uses `syn v1` instead of `syn v2`. Using `syn v1` causes most likely duplicate dependencies as described in #262.
There's a bug in https://github.com/GnomedDev/proc-macro-error-2/pull/2 that needs to be fixed before this pr can be merged.
Closes #78 
Closes #262
> chore(deps): Migrate from unmaintained proc-macro-error to proc-macro-error2

- .dicts/custom.txt
- benchmark-tests/Cargo.toml
- benchmark-tests/benches/test_lib_bench/all_args/expected_stderr.1a
- benchmark-tests/benches/test_lib_bench/all_args/expected_stderr.1b
- benchmark-tests/benches/test_lib_bench/all_args/expected_stdout.1a
- benchmark-tests/benches/test_lib_bench/all_args/expected_stdout.1b
- benchmark-tests/benches/test_lib_bench/all_args/expected_stdout.freebsd.1a
- benchmark-tests/benches/test_lib_bench/all_args/test_lib_bench_all_args.conf.yml
- benchmark-tests/benches/test_lib_bench/all_args/test_lib_bench_all_args.rs
- benchmark-tests/src/bench.rs
- benchmark-tests/src/lib.rs
- iai-callgrind-runner/src/api.rs
- iai-callgrind-runner/src/runner/bin_bench.rs
- iai-callgrind/src/lib_bench.rs
* Benchmark test which runs all callgrind command-line arguments to check for errors and correct terminal output
* `iai_callgrind::LibraryBenchmarkConfig` was missing the `Clone` derive impl.
> tests: Add benchmark test which runs all callgrind command-line arguments

- benchmark-tests/benches/test_bin_bench/tools/expected_stdout.1a
- benchmark-tests/benches/test_bin_bench/tools/expected_stdout.1b
- benchmark-tests/benches/test_bin_bench/tools/expected_stdout.freebsd.1a
- benchmark-tests/benches/test_bin_bench/tools/expected_stdout.freebsd.1b
- benchmark-tests/benches/test_lib_bench/all_args/expected_stdout.1a
- benchmark-tests/benches/test_lib_bench/all_args/expected_stdout.1b
- benchmark-tests/benches/test_lib_bench/all_args/expected_stdout.freebsd.1a
- benchmark-tests/benches/test_lib_bench/output_format/expected_stdout.1a
- benchmark-tests/benches/test_lib_bench/output_format/expected_stdout.1b
- benchmark-tests/benches/test_lib_bench/parts/expected_files.1.67.1.yml
- benchmark-tests/benches/test_lib_bench/parts/expected_files.yml
- benchmark-tests/benches/test_lib_bench/parts/expected_stdout
- benchmark-tests/benches/test_lib_bench/parts/expected_stdout.1.67.1
- benchmark-tests/benches/test_lib_bench/threads/expected_files.1a.yml
- benchmark-tests/benches/test_lib_bench/threads/expected_files.1b.yml
- benchmark-tests/benches/test_lib_bench/threads/expected_files.1d.yml
- benchmark-tests/benches/test_lib_bench/threads/expected_files.1e.yml
- benchmark-tests/benches/test_lib_bench/threads/expected_stdout.1a
- benchmark-tests/benches/test_lib_bench/threads/expected_stdout.1b
- benchmark-tests/benches/test_lib_bench/threads/expected_stdout.1d
- benchmark-tests/benches/test_lib_bench/threads/expected_stdout.1e
- benchmark-tests/benches/test_lib_bench/threads/expected_stdout.1f
- benchmark-tests/benches/test_lib_bench/threads/expected_stdout.1g
- benchmark-tests/benches/test_lib_bench/threads/expected_stdout.freebsd.1a
- benchmark-tests/benches/test_lib_bench/tools/expected_stdout.1a
- benchmark-tests/benches/test_lib_bench/tools/expected_stdout.1b
- iai-callgrind-runner/src/runner/callgrind/parser.rs
- iai-callgrind-runner/src/runner/format.rs
- iai-callgrind-runner/src/runner/tool/mod.rs
This change affects the terminal output which changes from
```text
...
...
```
to
```text
...
...
```
and the file names which change from `callgrind.some.1234.p1.t1.out` to `callgrind.some.1234.t1.p1.out`
> Change grouping by part -> thread to thread -> part

- benchmark-tests/benches/test_bin_bench/list_arg/expected_stdout
- benchmark-tests/benches/test_lib_bench/list_arg/expected_stdout
- iai-callgrind-runner/src/runner/format.rs
Right now `iai_callgrind_runner` outputs the tests using the *non-standard* `: bench`, causing it to be incompatible with third-party testing frameworks (i.e `cargo-nextest`: https://github.com/nextest-rs/nextest/pull/2374).
This changes the suffix to the one recommended by  cargo testing.
> refactor(format): use ': benchmark' suffix

- .dicts/custom.txt
- benchmark-tests/Cargo.toml
- benchmark-tests/benches/guide/lib_bench_regression.rs
- docs/src/SUMMARY.md
- docs/src/benchmarks/binary_benchmarks/important.md
- docs/src/benchmarks/binary_benchmarks/quickstart.md
- docs/src/benchmarks/library_benchmarks/compare_by_id.md
- docs/src/benchmarks/library_benchmarks/configuration/output_format.md
- docs/src/benchmarks/library_benchmarks/important.md
- docs/src/benchmarks/library_benchmarks/quickstart.md
- docs/src/benchmarks/library_benchmarks/setup_and_teardown.md
- docs/src/benchmarks/library_benchmarks/threads_and_subprocesses.md
- docs/src/cli_and_env/baselines.md
- docs/src/cli_and_env/output/terminal_output.md
- docs/src/regressions.md
* Update the code examples with the new summary line and regression stats
* Add section with the (callgrind) output format and give introductory examples on how to show cache misses
* Crosslink to CI in Regressions chapter and Comparison with baselines (#308)
> docs: Update and improve guide

- docs/src/installation/prerequisites.md
Just fixing a typo I noticed when reading the guide.
> doc(guide): Fix valgrind installation instructions for Alpine Linux

- .bumpversion/summary-schema.toml
- benchmark-tests/src/bench.rs
- iai-callgrind-runner/src/runner/summary.rs
The version in the generated `summary.json` and json output was still "3" instead of "4". This pr also adds a bump version file to automate future version bumps of the summary.
> Fix version in summary

- benchmark-tests/benches/test_bin_bench/main_and_group_setup_and_teardown/expected_stdout.2
- benchmark-tests/benches/test_bin_bench/setup_and_teardown/expected_stdout.2
- benchmark-tests/benches/test_lib_bench/main_and_group_setup_and_teardown/expected_stdout.2
- benchmark-tests/benches/test_lib_bench/main_and_group_setup_and_teardown/expected_stdout.3
- benchmark-tests/benches/test_lib_bench/single/expected_stdout.1
- benchmark-tests/benches/test_lib_bench/single/expected_stdout.2
- benchmark-tests/benches/test_lib_bench/threads/expected_stdout.1d
- benchmark-tests/benches/test_lib_bench/threads/expected_stdout.1e
- benchmark-tests/benches/test_lib_bench/threads/expected_stdout.1g
- iai-callgrind-runner/src/runner/format.rs
This happens especially with `--save-baseline=...`, so instead of
```
icount::icount_bench_yn_group::icount_bench_yn logspace:setup_yn()
Baselines:                        default|default
Instructions:                    24636546|24636546             (No change)
```
baselines are printed with `(old)` if the names are equal
```
icount::icount_bench_yn_group::icount_bench_yn logspace:setup_yn()
Baselines:                        default|default (old)
Instructions:                    24636546|24636546             (No change)
```
Related #338
> feat(baselines): Print baselines with same name with (old) suffix 

- iai-callgrind-runner/src/runner/args.rs
Sort fields alphabetically and instead use clap's display order to improve the sorting of the arguments in the --help message.
> Refactor `runner::args`

- benchmark-tests/benches/test_lib_bench/compare/expected_stdout.show-only-comparison
- benchmark-tests/benches/test_lib_bench/compare/test_lib_bench_compare.conf.yml
- iai-callgrind-runner/src/runner/args.rs
- iai-callgrind-runner/src/runner/format.rs
- iai-callgrind-runner/src/runner/tool/config.rs
This pr adds a command-line argument `--show-only-comparison` and env var `IAI_CALLGRIND_SHOW_ONLY_COMPARISON`. This option cancels showing the self comparisons of benchmarks and shows only the comparisons with other benchmarks when `compare_by_id` in a `library_benchmark_group` or `binary_benchmark_group` was given.
Curated example output:
```
test_lib_bench_compare::bubble_sort_compare_three::bench_bubble_sort_mixed_case case_3:vec! [2, 3, 1]
Comparison with bench_bubble_sort_best_case case_3:vec! [1, 2, 3]
Instructions:                          74|81                   (-8.64198%) [-1.09459x]
L1 Hits:                               94|104                  (-9.61538%) [-1.10638x]
LL Hits:                                1|1                    (No change)
RAM Hits: …
```
> Flag/ENV to show only comparisons with other benchmarks with `compare_by_id`
